# Generated by Django 5.1.7 on 2025-03-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_time',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_time',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
