# Generated by Django 5.1.7 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_time_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='contributors',
            options={'verbose_name_plural': 'Contributeurs'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name_plural': 'Problèmes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('back-end', 'Back-end'), ('front-end', 'Front-end'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=20, verbose_name='Type de projet'),
        ),
    ]
