# Generated by Django 5.1.7 on 2025-03-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='api.project', verbose_name='Projet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur'),
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user', 'project')},
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='projects',
        ),
    ]
