# Generated by Django 5.1.7 on 2025-03-26 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contributors_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
    ]
