# Generated by Django 5.2 on 2025-04-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_contributors_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='contributor',
            name='date_created',
            field=models.DateTimeField(default='2025-04-08T18:44:25.636337+02:00', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.issue', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
