# Generated by Django 5.2 on 2025-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_issue_options_contributor_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
