# Generated by Django 5.1.7 on 2025-03-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_be_contacted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_data_be_shared',
        ),
    ]
