# Generated by Django 5.1.7 on 2025-03-17 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_birthday_user_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 17, 52, 31, 568612)),
        ),
    ]
