# Generated by Django 5.1.7 on 2025-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_birthday_alter_user_can_be_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2025-03-26'),
        ),
    ]
